version: "3.2"
services:
  ipld-eth-server:
    restart: unless-stopped
    depends_on:
      - ${ipld_eth_server_db_dependency}
    build:
      context: ${vulcanize_ipld_eth_server}
      dockerfile: ./Dockerfile
    environment:
      IPLD_SERVER_GRAPHQL: "true"
      IPLD_POSTGRAPHILEPATH: http://graphql:5000
      ETH_SERVER_HTTPPATH: 0.0.0.0:8081
      VDB_COMMAND: "serve"
      ETH_CHAIN_CONFIG: "/tmp/chain.json"
      DATABASE_NAME: ${connecting_db_name}
      DATABASE_HOSTNAME: ${ipld_eth_server_db_dependency}
      DATABASE_PORT: 5432
      DATABASE_USER: "vdbm"
      DATABASE_PASSWORD: "password"
      ETH_CHAIN_ID: 99
      ETH_FORWARD_ETH_CALLS: $eth_forward_eth_calls
      ETH_PROXY_ON_ERROR: $eth_proxy_on_error
      ETH_HTTP_PATH: $eth_http_path
      WATCHED_ADDRESS_GAP_FILLER_ENABLED: $watched_address_gap_filler_enabled
      WATCHED_ADDRESS_GAP_FILLER_INTERVAL: $watched_address_gap_filler_interval
    volumes:
      - type: bind
        source: ../../start-up-files/ipld-eth-server/chain.json
        target: /tmp/chain.json
    ports:
      - "127.0.0.1:8081:8081"

  graphql:
    restart: unless-stopped
    depends_on:
      - ${ipld_eth_server_db_dependency}
    image: vulcanize/postgraphile:v1.0.1
    environment:
      PG_HOST: ${ipld_eth_server_db_dependency}
      PG_PORT: 5432
      PG_DATABASE: ${connecting_db_name}
      PG_USER: vdbm
      PG_PASSWORD: password
      SCHEMA: public,eth
    ports:
      - "127.0.0.1:5000:5000"
